// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sgokul961/timepeace-api-gateway/pkg/api"
	"github.com/sgokul961/timepeace-api-gateway/pkg/api/handler"
	"github.com/sgokul961/timepeace-api-gateway/pkg/client"
	"github.com/sgokul961/timepeace-api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*api.ServerHTTP, error) {
	adminClient := client.NewAdminClient(c)
	adminHandler := handler.NewAdminHandler(adminClient)
	userClient := client.NewUserClient(c)
	userHandler := handler.NewUserHandler(userClient)
	productClient := client.NewProductClient(c)
	productHandler := handler.NewProductHandler(productClient)
	serverHTTP := api.NewServerHTTP(adminHandler, userHandler, productHandler)
	return serverHTTP, nil
}
